# name: Run Unit Tests on push for Develop, on PR for master.

 on:
   pull_request:
     branches:
       - Shiv-Test
   push:
     branches:
       - moose-actions
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
       - uses: actions/setup-node@v1
         with:
           node-version: 12.x
       - run: npm test
